---
- include: Debian.yml
  when: ansible_os_family == 'Debian'
  become: yes
  
- include: nix.yml
  when: ansible_os_family != 'Windows'
  become: yes

- include: Darwin.yml
  when: ansible_os_family == 'Darwin'

- include: Windows.yml
  when: ansible_os_family == 'Windows'