---
# - name: Terraform - Ensure version to be installed exists
#   stat:
#     path: "/usr/local/bin/terraform{{ tf_install_version }}"
#   register: tf_bin_check

- name: Download Terraform binary
  ansible.builtin.get_url:
    #url: "{{ tf_download_url }}"
    url: "https://releases.hashicorp.com/terraform/{{ item }}/terraform_{{ item }}_{{ ansible_system | lower }}_amd64.zip"
    dest: /tmp
  loop: "{{ tf_versions }}"
  #when: tf_bin_check.stat.exists == False

# - name: Download Terraform binary
#   ansible.builtin.get_url:
#     url: "https://releases.hashicorp.com/terraform/{{ item }}/terraform_{{ item }}_{{ ansible_system | lower }}_amd64.zip"
#     dest: /tmp
#   loop: "{{ tf_versions }}"

# - name: Extract Terraform binary
#   unarchive:
#     src: "https://releases.hashicorp.com/terraform/{{ item }}/terraform_{{ item }}_{{ ansible_system | lower }}_amd64.zip"
#     dest: "/usr/local/bin/terraform-{{ item }}"
#     mode: 774
#     remote_src: yes
#     creates: "/usr/local/bin/terraform-{{ item }}"
#   loop: "{{ tf_versions }}"

- name: Extract Terraform binaries
  unarchive:
    src: "/tmp/{{ tf_archive_name }}"
    dest: "/usr/local/bin/terraform{{ tf_install_version }}"
    mode: 774
    remote_src: yes
    creates: "/usr/local/bin/terraform-{{ item }}"
  loop: "{{ tf_versions }}"
#   when: tf_bin_check.stat.exists == False

# - name: Extract Terraform binary to temp file
#   unarchive:
#     src: "/tmp/{{ tf_archive_name }}"
#     dest: /tmp
#     remote_src: yes
#   when: tf_bin_check.stat.exists == False

# - name: Move Terraform binary
#   copy:
#     src: /tmp/terraform
#     dest: "/usr/local/bin/terraform{{ tf_install_version }}"
#     mode: 774
#     remote_src: yes
#   when: tf_bin_check.stat.exists == False

# - name: Delete Terraform archive
#   file:
#     path: "/tmp/{{ tf_archive_name }}"
#     state: absent

- name: Create symlink for default Terraform binary version
  ansible.builtin.file:
    src: "/usr/local/bin/terraform{{ tf_default_version }}"
    dest: "/usr/local/bin/terraform"
    mode: 774
    state: link

- name: Ensure Terraform plugins directory exists for user on *nix
  ansible.builtin.file:
    path: "{{ tf_plugin_path[ansible_system].path }}"
    state: directory
    mode: "{{ tf_plugin_path[ansible_system].mode }}"